#EXERCISE NO. 4 - FUNCTION
#BANGAYAN, JUAN PAOLO S.
#GITHUB.COM/JUANPAOLOW
#JUANPAOLOBANGAYAN@YAHOO.COM

J = "Seize the day!"
P = "SeIzE tHe DaY!"

#ALL CHARACTERS IN UPPERCASE
print J.upper()

#ALL CHARACTERS IN LOWER CASE
print J.lower()

#CAPITALIZES THE FIRST CHARACTER OF EACH STRING
print J.title()

#CAPITALIZES THE FIRST CHARACTER OF THE SENTENCE
print J.capitalize()

#ALTERNATES THE SET OF CASE OF CHARACTER; IF CHARACTER IS IN UPPERCASE, IT WILL BE LOWERCASE AND VISE VERSA
print P.swapcase()
