#EXERCISE NO. 2 -  STRING MANIPULATION
#BANGAYAN, JUAN PAOLO S.
#GITHUB.COM/JUANPAOLOW
#JUANPAOLOBANGAYAN@YAHOO.COM

#NORMAL
J = "SIEZE THE DAY!"

print J

#REVERSE
print ' '.join(reversed(J))

#WORD REPLACE
print J.replace("SIEZE THE DAY", "KILL THEM HATERS")

